services:
  minio:
    image: bitnami/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin@2024
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Web Console
    volumes:
      - data:/bitnami/minio/data         # Dữ liệu object được lưu ở đây
      - config:/opt/bitnami/minio/config # File cấu hình MinIO
    command: minio server /bitnami/minio/data --console-address ":9001"

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: D:/minio-data  # Thư mục thật trên máy
      o: bind
  config:
    driver: local
