server:
  port: 8080
spring:
  application:
    name: backend-app
  profiles:
    active: @spring.profiles.active@
  datasource:
    url: jdbc:mysql://localhost:3306/book_rate_db?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    from: ${MAIL_FROM}
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    web:
      pageable:
        default-page-size: 10

jwt:
  access-token: TRrx3ZoD9xgevlM73MU8/ay9VO+8RJ7NjvFh8Ab0xoTsKzuPYwCOKDZugGYsVxroYRfP94DH6jBxBhFyBPaQQQ==
  refresh-token: TRrx3ZoD9xgevlM73MU8/yy9VO+8RJ7NjvFh5Ab0xoTsKuuPYwCOKDZugGYsVeroYRfP94DH6jBxBhFyBPaQQQ==
  reset-token: TRrx3ZoD9xgevlM73MU8/yy9VO+8RJ7NovFh5Ab0xoTsKuuPYwCOKDZugGYsVeyoYRfP94DH6jBxBhFyBPaQQQ==
  access-token-validity-in-seconds: 2700
  refresh-token-validity-in-seconds: 604800
  reset-token-validity-in-seconds: 300
minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin@2024
  bucket: book-rating