server:
  port: 8080
spring:
  application:
    name: backend-app
  profiles:
    active: @spring.profiles.active@
  datasource:
    url: "jdbc:mysql://localhost:3306/book_rate_db"
    username: root
    password: 123456
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
