server:
  port: 8082
spring:
  config:
    activate:
      on-profile: prod

openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}
    title: API Service
    version: v1.0.0

