server:
  port: 8081
spring:
  config:
    activate:
      on-profile: test
  mail:
    from: test@example.com
    host: smtp.gmail.com
    port: 587
    username: test@example.com
    password: testpassword

openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}
    title: API Service
    version: v1.0.0
